name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: myenvironment
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4.1.0
      
    - name: setup pip modules
      run: pip install toml
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install c-icap
        go build .

    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mahmoud011/icapeg
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: publish playbook artifact
      uses: actions/upload-artifact@v2
      with:
       name: playbooks
       path: ansible   
        

  deploy:
      name: Deploy to server 
      runs-on: ubuntu-latest
      env: 
        ansiblePass: ${{secrets.ANSIBLE_PASSWORD}}
      needs: build
      steps:
        - name: Install SSH key
          uses: actions/checkout@v3
        
#       - name: download artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: playbooks
#           path: ansible
          
#       - name: print ansiblePass
#         run: "echo $ansiblePass"
#       - name: print ${{secrets.DOCKER_USERNAME}}
#         run: echo ${{secrets.ANSIBLE_PASSWORD}}
#       - name: print ${{secrets.ANSIBLE_PASSWORD}}
#         run: "echo $secrets.ANSIBLE_PASSWORD"
      
        - name: Install SSH key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_KEY }}
            name: id_rsa # optional
            known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
            if_key_exists: replace # replace / ignore / fail; optional (defaults to fail)

        - name: Run playbook
          uses: dawidd6/action-ansible-playbook@v2
          with:
            playbook: playbook.yml
            directory: ansible
            options: |
              --inventory inventory.yml
              --extra-vars  ansible_password=${{secrets.ANSIBLE_PASSWORD}}
